name: "Docker"
on:
  workflow_dispatch:

  push:
    branches:
      - master
      - binder
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yml'
      - 'Dockerfile'
      - 'LICENSE'
      - 'ghc-parser/**'
      - 'html/**'
      - 'ihaskell-display/**'
      - 'ihaskell.cabal'
      - 'ipython-kernel/**'
      - 'main/**'
      - 'src/**'
      - 'stack.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81
    - uses: elgohr/Publish-Docker-Github-Action@f7aca2fea76a5218f3c76cd5933c3ba1d8008774
      with:
        name: daviddavo/ihaskell
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
